name: 'laravel_portfolio'

services:

    nginx:
        container_name: nginx
        image: nginx:alpine
        restart: always
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        depends_on:
            - app
            - postgres
        ports:
            - "80:80"
        networks:
            - app-network

    postgres:
        container_name: postgres
        build:
            context: .
            dockerfile: docker/postgres/Dockerfile
        restart: always
        environment:
            PGUSER: postgres
            POSTGRES_DB: laravel_portfolio
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        healthcheck:
            test: [ 'CMD', 'pg_isready' ]
            interval: 1s
            timeout: 5s
            retries: 5
        volumes:
            - pgdata:/data/postgres
        ports:
            - "${DB_PORT:-5432}:5432"
        networks:
            - app-network

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@email.example
            PGADMIN_DEFAULT_PASSWORD: secret
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "${PG_ADMIN_PORT:-8090}:80"
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app-network

    app:
        container_name: app
        user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            FPM_USER: www
            FPM_GROUP: www
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    supervisor:
        build:
            context: .
            dockerfile: docker/supervisor/Dockerfile
        container_name: supervisor
        volumes:
            - .:/var/www/
            - ./docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        depends_on:
            - app
            - postgres
            - redis
        restart: always
        networks:
            - app-network

    redis:
        container_name: redis
        image: redis:alpine
        restart: always
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
        ports:
            - "${REDIS_PORT:-6379}:6379"
        volumes:
            - cache:/data
        networks:
            - app-network

    redisinsight:
        container_name: redisinsight
        image: redis/redisinsight:latest
        restart: always
        ports:
            - "${REDIS_INSIGHT_PORT:-5540}:5540"
        volumes:
            - redisinsight:/data
        networks:
            - app-network

    smtp:
        image: mailhog/mailhog
        container_name: smtp
        restart: always
        ports:
            - "${MAIL_PORT:-1025}:1025"
            - "8100:8025"
        volumes:
            - smtp:/data
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    redisinsight:
    pgdata:
        driver: local
    pgadmin:
        driver: local
    cache:
        driver: local
    supervisor:
        driver: local
    smtp:
        driver: local
